ekf_local:
  ros__parameters:
    use_sim_time: false

    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # LIO-SAM: local pose (x, y, yaw)
    odom0: /lio_sam/mapping/odometry
    odom0_config: [
      true,  true,  false,
      false, false, true,
      false, false, false,
      false, false, false,
      false, false, false
    ]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_pose_rejection_threshold: 5.0

    # Wheel encoder: only forward/backward velocity vx
    odom1: /teker
    odom1_config: [
      false, false, false,
      false, false, false,
      true,  false, false,
      false, false, false,
      false, false, false
    ]
    odom1_differential: false
    odom1_relative: false
    odom1_queue_size: 10
    odom1_twist_rejection_threshold: 1.0


ekf_global:
  ros__parameters:
    use_sim_time: false

    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    publish_tf: false
    publish_acceleration: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map


    # navsat_transform output: global GPS position x, y
    odom0: /odometry/gps
    odom0_config: [
      true,  true,  false,
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, false
    ]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_pose_rejection_threshold: 5.0

    # Lidar localization global pose: x, y, yaw
    pose0: /pcl_pose
    pose0_config: [
      true,  true,  false,
      false, false, true,
      false, false, false,
      false, false, false,
      false, false, false
    ]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 10
    pose0_rejection_threshold: 2.0


navsat_transform_node:
  ros__parameters:
    use_sim_time: false

    frequency: 10.0
    delay: 3.0

    magnetic_declination_radians: 0.0
    yaw_offset: 0.0

    zero_altitude: true
    broadcast_utm_transform: false
    broadcast_utm_transform_as_parent_frame: false
    publish_filtered_gps: true

    # Heading comes from /imu/data, not from filtered odometry.
    use_odometry_yaw: false

    wait_for_datum: true
    datum: [41.0569538, 28.8204359, 0.0]
